<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>
<body>
<div class="w-50 mx-auto">
  <div class="container">
    <h1 class="display-4">O nás</h1>
    <p class="lead">Tento portál byl vytvořen za účelem školního projektu. Mnoho spokojených zážitků přejí
Jakub Dolejší, Tomáš Svěrák a Mark Menzyński.</p>
  </div>
</div>
</body>
</html>
