<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>
<body>



<div id="userModify">
    <h3 align="center">Pridani uzivatele</h3>
    <form method="post">
        <div class="generalSettings">
            <div class="item">
                <label for="jmeno">Jméno:</label>
                <input type="text" id="jmeno" name="jmeno" value="<?= $_POST['jmeno'] ?? '' ?>" placeholder="Jméno" required>
            </div>
            <div class="item">
                <label for="prijmeni">Příjmení:</label>
                <input type="text" id="prijmeni" name="prijmeni" value="<?= $_POST['prijmeni'] ?? '' ?>" placeholder="Příjmení" required>
            </div>
            <div class="item">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" value="<?= $_POST['email'] ?? '' ?>" placeholder="Email" required>
            </div>
            <div class="item">
                <label for="role">Role:</label>
                <input list="roles" name="role" id="role" required value="<?= $_POST['role'] ?? '' ?>">

                <datalist id="roles">
                    <option value="Registrovaný uživatel">
                    <option value="Redaktor">
                    <option value="Pokladní">
                    <option value="Admin">
                </datalist>

            </div>
            <div class="item">
                <label for="heslo">Heslo:</label>
                <input type="password" id="heslo" name="heslo" placeholder="Heslo" required>
            </div>
            <div class="item">
                <label for="kontrolniHeslo">Kontrolní Heslo:</label>
                <input type="password" id="kontrolniHeslo" name="kontrolniHeslo" placeholder="Heslo znovu" required>
            </div>
            <div class="settings">
                <input type=submit value="Uložit">
            </div>
            <div class="settings">
                <input type=button value="Zpět" onclick="window.location.href='/~xdolej09/IIS/admin'">
            </div>
        </div>
    </form>
</div>
</body>
</html>
