<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
</head>

<body>

<div class="mx-auto" style="width: 600px">
    <h3 class="text-center mb-4">Správce - Úprava informací uživatele</h3>
    <form method="post">
        <div class="container">
            <div class="row form-group">
                <div class="col-3">
                    <label for="firstName">Jméno</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="firstName" name="firstName" value="<?= $user['firstName'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="lastName">Příjmení</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="lastName" name="lastName" value="<?= $user['lastName'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="email">E-mail</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="email" name="email" value="<?= $user['email'] ?>">
                </div>
            </div>
            <div class="form-group row">
                <label for="role" class="col-3 col-form-label">Role</label>
                <div class="col-9">
                    <select class="custom-select form-control" id="role" name="role" required>
                        <option selected="selected"><?= $this->langMapper($user['role']) ?></option>
                        <option value="registrovaný uživatel">Registrovaný uživatel</option>
                        <option value="pokladní">Pokladní</option>
                        <option value="redaktor">Redaktor</option>
                        <option value="admin">Admin</option>
                    </select>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="is_verified">Ověřen</label>
                </div>
                <div class="col-9">
                    <input type="number" class="form-control" id="is_verified" name="is_verified" value="<?= $user['is_verified'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3"></div>
                <div class="col-9">
                    <input type="submit" class="btn btn-primary" id="submit" name="submit" value="Potvrdit" onclick="ajaxForm()">
                    <input type="button" class="btn btn-secondary" value="Zpět" onclick="window.location.href='admin'">
                </div>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    const opt = {};
    $("#role > option").each(function () {
        if (opt[$(this).text()]) {
            $(this).remove();
        }
        else {
            opt[$(this).text()] = $(this).val();
        }
    });
</script>
</body>
