<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>
<body>



<div id="userModify">
    <h3 align="center">Pridani uzivatele</h3>
    <form method="post">
        <div class="generalSettings">
            <div class="item">
                <label for="Jmeno">Jméno:</label>
                <input type="text" id="Jmeno" name="Jmeno" value="<?= isset($_POST['jmeno']) ? $_POST['jmeno'] : ''; ?>" placeholder="Jméno" required>
            </div>
            <div class="item">
                <label for="prijmeni">Příjmení:</label>
                <input type="text" id="Prijmeni" name="Prijmeni" value="<?= isset($_POST['prijmeni']) ? $_POST['prijmeni'] : ''; ?>" placeholder="Příjmení" required>
            </div>
            <div class="item">
                <label for="email">Email:</label>
                <input type="email" id="Email" name="Email" value="<?= isset($_POST['email']) ? $_POST['email'] : ''; ?>" placeholder="Email" required>
            </div>
            <div class="item">
                <label for="role">Role:</label>
                <input list="roles" name="Role" id="Role" required value="<?= isset($_POST['role']) ? $_POST['role'] : ''; ?>">

                <datalist id="roles">
                    <option value="Neregistrovaný uživatel">
                    <option value="Registrovaný uživatel">
                    <option value="Editor">
                    <option value="Pokladní">
                    <option value="Admin">
                </datalist>

            </div>
            <div class="item">
                <label for="Heslo">Heslo:</label>
                <input type="Heslo" id="Heslo" name="Heslo" placeholder="Heslo" required>
            </div>
            <div class="item">
                <label for="KontrolniHeslo">Kontrolní Heslo:</label>
                <input type="KontrolniHeslo" id="KontrolniHeslo" name="KontrolniHeslo" placeholder="Heslo znovu" required>
            </div>
            <div class="settings">
                <input type=submit value="Uložit">
            </div>
            <div class="settings">
                <input type=button value="Zpět" onclick="window.location.href='admin'">
            </div>
        </div>
    </form>
</div>
</body>
</html>
