<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
</head>

<body>
<form method="post">
    <div class="generalSettings">
        <div class="settings">
            <label for="firstName">Jmeno :</label>
            <input type="text" id="firstName" name="firstName" value="<?= $user['firstName'] ?>">
        </div>
        <div class="settings">
            <label for="lastName">Prijmeni :</label>
            <input type="text" id="lastName" name="lastName" value="<?= $user['lastName'] ?>">
        </div>
        <div class="settings">
            <label for="email">email :</label>
            <input type="text" id="email" name="email" value="<?= $user['email'] ?>">
        </div>
        <div class="settings">
            <label for="role">role :</label>

            <select name="role" id="role">
                <option selected="selected"><?= $this->langMapper($user['role']) ?></option>
                <option>registrovaný uživatel</option>
                <option>pokladní</option>
                <option>redaktor</option>
                <option>admin</option>
            </select>
        </div>
        <div class="settings">
            <label for="is_verified">Ověřen:</label>
            <input type="number" id="is_verified" name="is_verified" value="<?= $user['is_verified'] ?>">
        </div>
        <div class="settings">
            <input type="submit" id="submit" name="submit" value="Potvrdit" onclick="ajaxForm()">
        </div>
        <div class="settings">
            <input type=button value="Zpet" onclick="window.location.href='admin'">
        </div>
    </div>
</form>

<script type="text/javascript">
    const opt = {};
    $("#role > option").each(function () {
        if (opt[$(this).text()]) {
            $(this).remove();
        }
        else {
            opt[$(this).text()] = $(this).val();
        }
    });
</script>
</body>
