<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="Views/CSS/baseStyle.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<ul>
    <li><a href="home">Domů</a></li>

    <li><a href="search">Hledat</a></li>
    <li id="auth">
		<?php
		if (!empty($_SESSION['user_id'])) {
			echo '<a href="auth">Auth stuff</a>';
		} ?>
    </li>
    <li id="registration">
		<?php
		if (empty($_SESSION['user_id'])) {
			echo '<a href="registration">Registrace</a>';
		} ?>
    </li>
    <li style="float:right" id="about"><a href="about">O nás</a></li>
    <li style="float: right">
		<?php
		if (empty($_SESSION['user_id'])) {
			echo '<a href="login">Přihlásit</a>';
		} else {
			echo '<a href="logout">Odhlásit</a>';
		}
		?>
    </li>
    <li style="float:right" id="settings">
		<?php
		if (!empty($_SESSION['user_id'])) {
			echo '<a href="settings">Nastavení</a>';
		}
		?>
    </li>
    <li style="float:right" id="settings">
		<?php
		if (!empty($_SESSION['user_id'])) {
			echo '<a href="ticket">Lístky</a>';
		}
		?>
    </li>
    <li style="float: right">
        <input type="text" placeholder="Zadejte název události..." name="search">
        <input type=button class="searchButton" value="Hledat">
    </li>
</ul>

<article>
    <!--	--><?php //$this->view = $this->controller->view; // nastaveni pohledu aktualniho kontroleru
	$this->render(); ?>
</article>

</body>
</html>
