<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>

<body>
<!-- <div class="searchGeneral">
    Rezervace pro událost - pokladní:
    <div>

        <form method="post">
            <div id="text">
                <div class="item">
                    <label for="date">Datum</label>
                    <input type="date" name="date" id="date" size="30" value="<?php echo date('Y-m-d'); ?>">
                </div>
                <div>
                    <label for="begin">Zacatek</label>
                    <input type="time" name="begin" id="begin">
                </div>
                <div class="item">
                    <label for="type">Typ</label>
                    <input list="browsers" name="type" id="type">

                    <datalist id="browsers">
                        <option value="Film">
                        <option value="Prednaska">
                        <option value="Prezentace">
                        <option value="Divadelní představení">
                        <option value="Stand-up">
                    </datalist>
                </div>
                <div class="item">
                    <label for="name" class="name">Nazev</label>
                    <input type="text" placeholder="Zadejte nazev udalosti" name="name" id="name">
                </div>
            </div>
            <button type="submit"><i class="fa fa-search"> Hledat</i></button>
            <input type="button" onclick="location.href= 'cashier'" value="Zpět">
        </form>
    </div>
    <?php foreach ($events as $event) : ?>
        <div class="concreteItem">
            <input type="button" onclick="location.href = 'cashier/reservation/<?= str_replace(' ', '%20',
                $event['type']) ?>/<?= str_replace(' ', '%20', $event['name']) ?>/<?= $event['label'] ?>/<?=
            str_replace(' ', '%20', $event['begin']) ?>';"
                   value="Rezervovat"/>

            <?php foreach ($event as $item => $value) : ?>
                <?= $this->langMapper($item) ?> : <?= $value ?> &nbsp;|
            <?php endforeach ?>
        </div>
    <?php endforeach ?>
</div> -->

<div class="mx-auto">
    <h2 class="text-center mb-4">Rezervace pro událost - pokladní</h2>
    <form method="post" class="mx-auto" style="width: 600px">
        <div class="form-group row">
            <label for="date" class="col-3 col-form-label">Datum</label>
            <div class="col-9">
                <input type="date" name="date" id="date" class="form-control" value="<?= date('Y-m-d') ?>">
            </div>
        </div>
        <div class="form-group row">
            <label for="begin" class="col-3 col-form-label">Začátek</label>
            <div class="col-9">
                <input type="time" name="begin" id="begin" class="form-control">
            </div>
        </div>
        <div class="form-group row">
            <label for="type" class="col-3 col-form-label">Typ</label>
            <div class="col-9">
                    <select class="custom-select form-control" id="type" name="type">
                        <option></option>
                        <option value="Film">Film</option>
                        <option value="Prednaska">Přednáška</option>
                        <option value="Prezentace">Prezentace</option>
                        <option value="Divadelni predstaveni">Divadelní představení</option>
                        <option value="Stand-up">Stand-up</option>
                    </select>

            </div>
        </div>
        <div class="form-group row">
            <label for="name" class="col-3 col-form-label">Název</label>
            <div class="col-9">
                <input type="text" placeholder="Zadejte název události" name="name" id="name" class="form-control">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3"></div>
            <div class="col-9">
            <button type="submit" class="btn btn-primary">Hledat</i></button>
        </div>
    </form>
</div>

<table class="table mt-5 w-100">
    <thead class="table-primary">
        <tr>
            <th></th>
            <th scope="col">Jméno</th>
            <th scope="col">Typ</th>
            <th scope="col">Žánr</th>
            <th scope="col">Datum</th>
            <th scope="col">Začátek</th>
            <th scope="col">Label</th>
            <th scope="col">Cena</th>
            <th scope="col">Typ platby</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($events as $event) : ?>
        <tr>
            <td>
                <button class="btn btn-outline-secondary" onclick="location.href='search/event/<?= str_replace(' ', '%20', $event['name']) ?> ';">
                    <i class="fas fa-info"></i>
                </button>
            </td>
            <?php foreach ($event as $value) : ?>
            <td>
                <?= $value ?>
            </td>
            <?php endforeach ?>
            <td>
                <button class="btn btn-primary " onclick="location.href = 'cashier/reservation<?=
                str_replace(' ', '%20', $event['type'])?>/<?= str_replace(' ', '%20', $event['name'])
                ?>/<?= str_replace(' ', '%20', $event['label'])?>/<?= str_replace(' ' , '%20', $event['begin'])?>'">
                    Rezervovat
                </button>
            </td>

        </tr>
        <?php endforeach ?>
    </tbody>
</table>




</body>