<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>
<body>
<div class="welcome">
    <h3>Správa rezervací</h3>
</div>

    <div>
        <input type="submit" value="Přidat rezervaci" onclick=window.location.href='/~xdolej09/IIS/cashier/add/'>
        <input type="submit" value="Vyhledat rezervaci" onclick=window.location.href='/~xdolej09/IIS/cashier/confirm/'>
    </div>

</form>
</body>
</html>
