<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>
<body>
<div class="mx-auto" style="width: 800px">
    <h3 class="mb-3">Vyhledání rezervace (nějak ošetřit aby mohl zadat pouze jedno pole)</h3>
    <form method="post" class="mb-3">
        <div class="container">
            <div class="row form-group">
                <div class="col-3">
                    <label for="lastName">Číslo rezervace</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="id" name="id">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3"> 
                    <label for="email">Email</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="email" name="email">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="hall">Označení sálu</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="hall" name="hall">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="event">Název události</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="event" name="event">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3"></div>
                <div class="col-9">
                    <input type="submit" class="btn btn-primary" value="Hledat">
                    <input type="button" class="btn btn-secondary" onclick="location.href= 'cashier'" value="Zpět">
                </div>
            </div>
        </div>
    </form>

    <table class="table w-auto">
        <thead class="table-primary">
            <tr class="text-center">
                <th>Potvrdit úhradu</th>
                <th>Zrušit rezervaci</th>
                <th>ID</th>
                <th>Jméno</th>
                <th>Začátek</th>
                <th>Datum</th>
                <th>Cena</th>
                <th>Sedadlo</th>
                <th>Sál</th>
                <th>Způsob platby</th>
                <th>Uhrazeno</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($tickets as $ticket) : ?>
            <tr>
                <td class="pr-0 text-center w-auto">
                    <!--- Pouze pokud nebylo zaplaceno/ neprobehlo--->
                    <button type="button" onclick="location.href= 'cashier/search/confirm/<?= str_replace (' ', '%20', $ticket['id']) ?>'"
                        <?php if ($ticket['is_paid'] === 'Ano'): ?>
                            disabled title="Již zaplaceno" class="btn btn-secondary py-1 px-2"
                        <?php elseif (($ticket['date'] < $todayDate) || (($ticket['begin'] < $currentTime) && ($ticket['date'] <= $todayDate))): ?>
                            disabled title="Nelze zaplatit - událost již proběhla" class="btn btn-secondary py-1 px-2"
                        <?php else: ?>
                            class="btn btn-primary py-1 px-2" 
                        <?php endif ?>>
                        <i class="fas fa-check"></i>
                        </button>
                </td>
                <td class="px-0 text-center">
                    <button type="button" class="btn btn-primary px-2 py-1" onclick="location.href= 'cashier/search/remove/<?=
                    str_replace
                    (' ',
                        '%20', $ticket['id'])
                    ?>';">
                    <i class="fas fa-minus"></i>
                    </button>
                </td>

                <?php foreach ($ticket as $item => $value) : ?>
                <td>
                <?= $value ?>
                </td>
                <?php endforeach ?>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<p id="msg"></p>
</body>
</html>
