<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>
<body>
<div class="mx-auto" style="width: 600px">
    <h3>Správa rezervací</h3>
    <input type="submit" class="btn btn-primary" value="Přidat rezervaci" onclick=window.location.href='cashier/add/'>
    <input type="submit" class="btn btn-primary" value="Vyhledat rezervaci" onclick=window.location.href='cashier/search/'>
</div>

</form>
</body>
</html>
