<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>
<body>
<div class="welcome">
    Edit reservations:
</div>
<form method="post">
    <div class="searchGeneral">
        <label for="searchEmail">Zadejte email pro zobrazeni listku</label>
        <input type="text" id="searchEmail" name="searchEmail">
        <input type="submit" class="fa fa-search" value="hledat">
    </div>

	<?php foreach ($tickets as $ticket) : ?>
        <div class="concreteItem">
            <input type="button" onclick="location.href = 'cashier/<?= str_replace(' ', '%20',
				$ticket['price']) ?>/<?= str_replace(' ', '%20', $ticket['seat']) ?>/<?= $ticket['discount']
			?>/<?=
			str_replace(' ', '%20', $ticket['email']) ?>';"
                   value="Upravit"/>

			<?php foreach ($ticket as $item => $value) : ?>
				<?= $item ?> : <?= $value ?> &nbsp;|
			<?php endforeach ?>
        </div>
	<?php endforeach ?>
</form>
</body>
</html>
