<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>

<body>
<div class="generalSettings">

	<?php foreach ($event as $item => $value) : ?>
        <div class="concreteItem">
			<?php if ($item === 'image') {
				break;
			} ?>
			<?= $this->langMapper($item)?> : <?= $value ?> &nbsp;|
        </div>
	<?php endforeach ?>

    <img src= <?= $event['image'] ?> alt="">
    <input type=button value="Zpet" onclick="window.location.href='/~xdolej09/IIS/search'">
</div>
</body>
