<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
</head>

<body>

<div class="mx-auto" style="width: 600px">
    <h3 class="text-center mb-4">Editor - Úprava události</h3>
    <form method="post">
        <div class="container">
            <div class="row form-group">
                <div class="col-3">
                    <label for="name">Jméno</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="name" name="name" value="<?= $works['name'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="type">Typ</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="type" name="type" value="<?= $works['type'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="genre">Žánr</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="genre" name="genre" value="<?= $works['genre'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="actors">Herci</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="actors" name="actors" value="<?= $works['actors'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="ranking">Hodnocení</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="ranking" name="ranking" value="<?= $works['ranking'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="description">Popis</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="description" name="description" value="<?= $works['description'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="description">Obrázek</label>
                </div>
                <div class="col-9">
                    <input type="file" class="form-control-file" id="image" name="image">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3"></div>
                <div class="col-9">
                    <input type="submit" class="btn btn-primary" id="submit" name="submit" value="Potvrdit" onclick="ajaxForm()">
                    <input type="button" class="btn btn-secondary" value="Zpět" onclick="window.location.href='editor/works'">
                </div>
            </div>
        </div>
    </form>
</div>

</body>
