<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
</head>

<body>
<form method="post">
    <div class="generalSettings">
        <div class="settings">
            <label for="label">label :</label>
            <input type="text" id="label" name="label">
        </div>
        <div class="settings">
            <label for="seat_schema">seat_schema :</label>
            <input type="text" id="seat_schema" name="seat_schema">
        </div>
        <div class="settings">
            <label for="capacity">capacity :</label>
            <input type="number" id="capacity" name="capacity">
        </div>
        <div class="settings">
            <label for="column_count">column_count:</label>
            <input type="number" id="column_count" name="column_count">
        </div>
        <div class="settings">
            <label for="row_count">row_count:</label>
            <input type="number" id="row_count" name="row_count">
        </div>
        <div class="settings">
            <input type="submit" id="submit" name="submit" value="Potvrdit" onclick="ajaxForm()">
        </div>
        <div class="settings">
            <input type=button value="Zpet" onclick="window.location.href='editor/halls'">
        </div>
    </div>
</form>
</body>
