<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="Views/JS/actions.js"></script>
</head>
<body>

<div class="mx-auto" style="width: 600px">
    <h3 class="mb-3">Správa kina</h3>
    <input type="submit" class="btn btn-primary" value="Správa sálu" onclick=window.location.href='editor/halls'>
    <input type="submit" class="btn btn-primary" value="Správa kulturních událostí" onclick=window.location.href='editor/events'>
    <input type="submit" class="btn btn-primary" value="Správa kulturních děl" onclick=window.location.href='editor/works'>
</div>
</body>
</html>
