<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
</head>

<body>
<div class="mx-auto" style="width: 600px">
    <h3 class="text-center mb-4">Editor - Úprava sálu</h3>
    <form method="post">
        <div class="container">
            <div class="row form-group">
                <div class="col-3">
                    <label for="label">Číslo sálu</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="label" name="label" value="<?= $hall['label'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="seat_schema">Schéma sálu</label>
                </div>
                <div class="col-9">
                    <input type="text" class="form-control" id="seat_schema" name="seat_schema" value="<?= $hall['seat_schema'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="capacity">Kapacita</label>
                </div>
                <div class="col-9">
                    <input type="number" class="form-control" id="capacity" name="capacity" value="<?= $hall['capacity'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="column_count">Sedadel v řadě</label>
                </div>
                <div class="col-9">
                    <input type="number" class="form-control" id="column_count" name="column_count" value="<?= $hall['column_count'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="row_count">Počet řad</label>
                </div>
                <div class="col-9">
                    <input type="number" class="form-control" id="row_count" name="row_count" value="<?= $hall['row_count'] ?>">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3"></div>
                <div class="col-9">
                    <input type="submit" class="btn btn-primary" id="submit" name="submit" value="Potvrdit" onclick="ajaxForm()">
                    <input type=button class="btn btn-secondary" value="Zpět" onclick="window.location.href='editor/halls'">
                </div>
            </div>
        </div>
    </form>
</div>
</body>
