<!DOCTYPE html>

<html lang="cs-cz">
<head>
	<meta charset="UTF-8"/>
	<base href="/localhost"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
</head>
<?php
$hallIds = $events[0];
$workIds = $events[1];
?>
<body>
<form method="post">
	<div class="generalSettings">
        <div class="settings">
            <label for="id_hall">id_hall:</label>
            <select  id="id_hall" name="id_hall">
	        <?php foreach ($hallIds as $ids) {
		        foreach ($ids as $id) {
			        echo "<option value=$id >$id</option>";
		        }
	        }?>

            </select>
        </div>
        <div class="settings">
            <label for="id_culture_work">id_culture_work:</label>
            <select id="id_culture_work" name="id_culture_work">
	            <?php foreach ($workIds as $ids) {
		            foreach ($ids as $id) {
			            echo "<option value=$id >$id</option>";
		            }
	            }?>

            </select>
        </div>
		<div class="settings">
			<label for="date">date :</label>
			<input type="date" id="date" name="date">
		</div>
		<div class="settings">
			<label for="begin">begin :</label>
			<input type="time" id="begin" name="begin">
		</div>
		<div class="settings">
			<label for="end">end:</label>
			<input type="time" id="end" name="end">
		</div>
		<div class="settings">
			<label for="price">price:</label>
			<input type="number" id="price" name="price">
		</div>
		<div class="settings">
			<input type="submit" id="submit" name="submit" value="Potvrdit" onclick="ajaxForm()">
		</div>
		<div class="settings">
			<input type=button value="Zpet" onclick="window.location.href='editor/events'">
		</div>
	</div>
</form>
</body>
