<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="Views/JS/actions.js"></script>
</head>
<body>

<form method="post">
    <div class="generalSettings">
        <div class="settings">
            <label for="price">adadsd</label>
            <input type="text" id="price" name="price">
        </div>
        <div>
            <input type="submit" onclick="return editorAjax()">
        </div>
    </div>
	<?= var_dump($price) ?>
</form>
<p id="msg"></p>
</body>
</html>
