<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="Views/JS/actions.js"></script>
</head>
<body>

<div class="mx-auto" style="width: 700px">
	<table class="table table-striped w-auto mb-3">
    <thead class="table-primary">
		<tr class="text-center">
			<th>Upravit</th>
			<th>Smazat</th>
			<th>ID</th>
			<th>Sál</th>
			<th>Schéma</th>
			<th>Kapacita</th>
			<th>Sedadel v řadě</th>
			<th>Počet řad</th>
		<tr>
	</thead>
	<tbody>
		<?php foreach ($hall as $event) : ?>
		<tr class="text-center">
			<td>
				<button type="button" class="btn btn-primary px-2 py-1" onclick="location.href= 'editor/halls/edit/<?= str_replace
					(' ',
						'%20', $event['id'])
					?>';">
					<i class="fas fa-edit"></i>
				</button>
			</td>
			<td>
				<button type="button" class="btn btn-secondary px-2 py-1" value="smazat" onclick="location.href= 'editor/halls/remove/<?=
					str_replace
					(' ',
						'%20', $event['id'])
					?>';">
					<i class="fas fa-trash-alt"></i>
				</button>
			</td>

			<?php foreach ($event as $item => $value) : ?>
				<td class="align-middle">
				<?= $value ?>
				</td>
			<?php endforeach ?>
		</tr>
		<?php endforeach ?>
	</tbody>
</table>

<input type="button" class="btn btn-primary mr-1" value="Přidat nový sál" onclick="location.href='editor/halls/add'">
<input type="submit" class="btn btn-secondary" value="Zpět" onclick=window.location.href='editor'>

</div>

</body>
</html>
