<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
</head>
<?php
$hallIds = $events[0];
$workIds = $events[1];
?>
<body>

<div class="mx-auto" style="width: 600px">
    <form method="post">
        <div class="container">
            <div class="row form-group">
                <div class="col-3">
                    <label for="id_hall">Sál</label>
                </div>
                <div class="col-9">
                    <select id="id_hall" class="form-control" name="id_hall">
                    <?php foreach ($hallIds as $ids) {
                        foreach ($ids as $id) {
                            echo '<option value = "'.$id.'" > '.$id.'</option>';
                        }
                    } ?>
                    </select>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="id_culture_work">Dílo</label>
                </div>
                <div class="col-9">
                    <select id="id_culture_work" class="form-control" name="id_culture_work">
                    <?php foreach ($workIds as $ids) {
                        foreach ($ids as $id) {
                            echo '<option value = "'.$id.'" > '.$id.'</option>';
                        }
                    } ?>
                    </select>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="date">Datum</label>
                </div>
                <div class="col-9">
                    <input type="date" class="form-control" id="date" name="date">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="begin">Začátek</label>
                </div>
                <div class="col-9">
                    <input type="time" class="form-control" id="begin" name="begin">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="end">Konec</label>
                </div>
                <div class="col-9">
                    <input type="time" class="form-control" id="end" name="end">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="price">Cena</label>
                </div>
                <div class="col-9">
                    <input type="number" class="form-control" id="price" name="price">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3"></div>
                <div class="col-9">
                    <input type="submit" class="btn btn-primary" id="submit" name="submit" value="Potvrdit" onclick="ajaxForm()">
                    <input type=button class="btn btn-secondary" value="Zpět" onclick="window.location.href='editor/events'">
                </div>
            </div>
        </div>
    </form>
</div>

</form>
</body>
