<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="Views/JS/actions.js"></script>
</head>
<body>

<div class="settings">
    <input type="submit" value="Sprava salu" onclick=window.location.href='/~xdolej09/IIS/editor/halls'>
    <input type="submit" value="Sprava kulturnich udalosti" onclick=window.location.href='/~xdolej09/IIS/editor/events'>
    <input type="submit" value="Sprava kulturnich del" onclick=window.location.href='/~xdolej09/IIS/editor/works'>
</div>
</body>
</html>
