<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="Views/JS/actions.js"></script>
</head>
<body>

<div class="mx-auto" style="width: 1000px">
	<h2 class="mb-3">Správa událostí</h2>
	<table class="table table-striped w-auto mb-3">
    <thead class="table-primary">
		<tr class="text-center">
			<th>Upravit</th>
			<th>Smazat</th>
			<th>ID</th>
			<th>Jméno</th>
			<th>Typ</th>
			<th>Hodnocení</th>
			<th>Herci</th>
			<th>Popis</th>
			<th>Žánr</th>
		<tr>
	</thead>
	<tbody>
		<?php foreach ($works as $event) : ?>
		<tr class="text-center">
			<td class="align-middle">
				<button type="button" class="btn btn-primary px-2 py-1" onclick="location.href= 'editor/works/edit/<?= str_replace
				(' ',
					'%20', $event['id'])
				?>';">
				<i class="fas fa-edit"></i>
				</button>
			</td>
			<td class="align-middle">
				<button type="button" class="btn btn-secondary px-2 py-1" onclick="location.href= 'editor/works/remove/<?=
				str_replace
				(' ',
					'%20', $event['id'])
				?>';">
				<i class="fas fa-trash-alt"></i>
				</button>
			</td>
			<?php foreach ($event as $item => $value) : ?>
				<td class="align-middle">
				<?= $value ?>
				</td>
			<?php endforeach ?>
		</tr>
		<?php endforeach ?>
	</tbody>
	</table>

<input type="button" class="btn btn-primary mr-1" value="Přidat nové dílo" onclick="location.href='editor/works/add'">
<input type="submit" class="btn btn-secondary" value="Zpět" onclick=window.location.href='editor'>

</div>

</body>
</html>
