<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>
<body>

<div class="w-50 mx-auto">
  <div class="container">
    <h1 class="display-4">Kino</h1>
    <p class="lead">Nevíte co s načatým večerem? Chcete potěšit Vaši drahou polovičku či Vás prostě už omrzela hospoda s přáteli a toužíte po něčem jinačím? V našem kulturním portálu
    si určitě vyberete! Nabízíme různorodé kulturní představení, promítání filmů, stand-up show, přednášky a mnohé další. 
    U nás můžete spojit kulturu, vzdělání a zábavu jednodušeji, než kdy předtím.</p>
  </div>
</div>

</body>
</html>
