<!DOCTYPE html>

<html lang="cs-cz">
<head>
	<meta charset="UTF-8"/>
	<base href="/localhost"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>
<body>
<form method="post" class="mx-auto" style="width: 600px">
	<h2 class="text-center mb-4">Přihlášení</h2>
	<div class="form-group row">
		<label for="email" class="col-3 col-form-label">E-mail</label>
		<div class="col-9">
			<input type="text" name="email" class="form-control" id="email" value="<?= isset($_POST['email']) ? $_POST['email'] : ''; ?>" placeholder="E-mail" required/>
		</div>
	</div>
	<div class="form-group row">
		<label for="password" class="col-3 col-form-label">Heslo</label>
		<div class="col-9">
        	<input type="password" name="password" class="form-control" id="password" placeholder="Password" required/>
		</div>
	</div>
	<div class="form-group row">
        <div class="col-3"></div>
            <button type="submit" class="mx-3 btn btn-primary">Přihlásit se</div>
        </div>
	</div>
</form>

</body>