<!DOCTYPE html>

<html lang="cs-cz">
<head>
	<meta charset="UTF-8"/>
	<base href="/localhost"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>
<body>
<form method="post">
<div id="login-box">
    <div class="searchGeneral">
		<h1>Sign in</h1>
        <input type="text" name="email" id="email" value="<?= isset($_POST['email']) ? $_POST['email'] : ''; ?>" placeholder="E-mail" required/>
        <input type="password" name="password" id="password" placeholder="Password" required/>
		<input type="submit" value="Sign me in" />
	</div>
</div>
</form>

</body>