<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="Views/JS/actions.js"></script>
</head>
<body>
<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="Views/JS/actions.js"></script>
</head>
<body>
<form method="post">
    <div class="generalSettings">
        <div class="settings">
            <label for="label">Label:</label>
            <input type="text" id="label" name="label" placeholder="label">
        </div>
        <div class="settings">
            <label for="schema">Schema:</label>
            <input type="text" id="schema" name="schema" placeholder="schema">
        </div>
        <div class="settings">
            <label for="capacity">Capacity:</label>
            <input type="text" id="capacity" name="capacity" placeholder="capacity">
        </div>
        <div class="settings">
            <label for="row">Row Count:</label>
            <input type="text" id="row" name="row" placeholder="row count">
        </div>
        <div class="settings">
            <label for="column">Column Count:</label>
            <input type="text" id="column" name="column" placeholder="column count">
        </div>
        <div class="settings">
            <input type=submit value="Vytvorit">
        </div>
        <div class="settings">
            <input type=button value="Zpet" onclick="window.location.href='editor/halls'">
        </div>
</form>
</body>
</html>

</body>
</html>
