<!DOCTYPE html>

<html lang="cs-cz">
<head>
	<meta charset="UTF-8"/>
	<base href="/localhost"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>
<body>

<form method="post">
	<div id="login-box">
	  <div class="left">
	    <h1>Sign up</h1>

	    <input type="text" name="firstName" id="firstName" placeholder="First Name" />
	    <input type="text" name="lastName" id="lastName" placeholder="Last Name" />
	    <input type="text" name="email" id="email" placeholder="E-mail" />
	    <input type="password" name="password" id="password" placeholder="Password" />
	    <input type="password" name="password2" id="password2" placeholder="Retype password" />

	    <input type="submit" value="Sign me up" />
	  </div>
	</div>
</form>
</body>