<!DOCTYPE html>

<html lang="cs-cz">
<head>
	<meta charset="UTF-8"/>
	<base href="/localhost"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>
<body>
    <form method="post" class="mx-auto" style="width: 600px">
        <h2 class="text-center mb-4">Registrace</h2>
        <div class="form-group row">
            <label for="firstName" class="col-3 col-form-label">Jméno</label>
            <div class="col-9">
                <input type="text" name="firstName" id="firstName" class="form-control" value="<?= isset($_POST['firstName']) ? $_POST['firstName'] : ''; ?>" placeholder="Jméno" required/>
            </div>
        </div>
        <div class="form-group row">
            <label for="lastName" class="col-3 col-form-label">Příjmení</label>
            <div class="col-9">
                <input type="text" name="lastName" id="lastName" class="form-control" value="<?= isset($_POST['lastName']) ? $_POST['lastName'] : ''; ?>" placeholder="Příjmení" required/>
            </div>
        </div>
        <div class="form-group row">
            <label for="email" class="col-3 col-form-label">E-mail</label>
            <div class="col-9">
                <input type="email" name="email" id="email" class="form-control" value="<?= isset($_POST['email']) ? $_POST['email'] : ''; ?>" placeholder="E-mail" required/>
            </div>
        </div>
        <div class="form-group row">
            <label for="password" class="col-3 col-form-label">Heslo</label>
            <div class="col-9">
                <input type="password" name="password" id="password" class="form-control" placeholder="Heslo" required/>
            </div>
        </div>
        <div class="form-group row">
            <label for="controlPassword" class="col-3 col-form-label">Potvrzení hesla</label>
            <div class="col-9">
                <input type="password" name="controlPassword" id="controlPassword" class="form-control" placeholder="Potvrzení hesla" required/>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3"></div>
            <button type="submit" class="mx-3 btn btn-primary">Zaregistrovat</div>
        </div>
    </form>

</body>