<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>
<body>
<form method="post" class="mx-auto" style="width: 600px">
    <h2 class="text-center">Rezervace pro událost</h2><br>
    <div class="form-group row">
        <label for="firstName" class="col-3 col-form-label">Jméno</label>
        <div class="col-9">
            <input type="text" name="firstName" id="firstName" class="form-control" value="<?= isset($_POST['firstName']) ? $_POST['firstName'] : ''; ?>" placeholder="Jméno" required/>
        </div>
    </div>
    <div class="form-group row">
        <label for="lastName" class="col-3 col-form-label">Příjmení</label>
        <div class="col-9">
            <input type="text" name="lastName" id="lastName" class="form-control" value="<?= isset($_POST['lastName']) ? $_POST['lastName'] : ''; ?>" placeholder="Příjmení" required/>
        </div>
    </div>
    <div class="form-group row">
        <label for="email" class="col-3 col-form-label">E-mail</label>
        <div class="col-9">
            <input type="email" name="email" id="email" class="form-control" value="<?= isset($_POST['email']) ? $_POST['email'] : ''; ?>" placeholder="E-mail" required/>
        </div>
    </div>

    <table class="w-auto m-auto table table-borderless" data-toggle="buttons">
        <tr>
            <td></td>
            <td colspan="<?=$halls['column_count']?>" class="">
                <button class="btn btn-secondary btn-block" disabled>plátno / jeviště</button>
            </td>
        </tr>
        <?php for($i = 0; $i < $halls['row_count']; $i++): ?>
            <?php $x = chr($i + 65);?>
            <tr>
                <td class="m-auto p-0 align-middle text-secondary">
                    <?= chr($i + 65) ?>
                </td>
                <td class="w-auto px-0 py-0 pb-1 border-bottom border-dark border-skip-last">
                    <?php for($j = 0; $j < $halls['column_count']; $j++): ?>
                    <?php $y = $j+1;?>
                    <?php if(!in_array(chr($i + 65).($j+1), $reservedSeats)): ?>
                    <label class="m-0 pr-1 p-0 btn chair btn-outline-success">
                        <input type="radio" class="w-0 m-0 p-0" name="seat" id="seat" value="<?=chr($i + 65).($j+1)?>" autocomplete="off" required>
                        <?php else :?>
                        <label class="m-0 pr-1 p-0 btn chair btn-outline-danger">
                            <input type="radio" class="w-0 m-0 p-0" name="seat" id="seat" value="<?=chr($i + 65).($j+1)?>" autocomplete="off" disabled title="Sedadlo obsazeno">
                            <?php endif?>
                            <i class="m-0 p-0 fas fa-couch"></i>
                        </label>
                        <?php endfor ?>
                </td>
            </tr>
        <?php endfor ?>

    </table>
    <br>

    <div class="form-group row">
    <label class="col-3 col-form-label" for="type">Typ platby</label>
    <div class="col-20">
    <select class="custom-select form-control" id="type" name="type">
        <option value="na pokladně">Na pokladně</option>
        <option value="předem">Předem</option>
    </select>
    </div>
    </div>

    <div >
        <input class="btn btn-primary" type="submit" value="Potvrdit">
        <input class="btn btn-secondary" type=button value="Zpět" onclick="window.location.href='search'">
    </div>
</form>

</body>