<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>

<body>
<div class="searchGeneral">
    Rezervace pro udalost:
	<div>
        <form method="post">
            <div class="item">
                <label for="column">Sloupec</label>
                <input type="number" id="column" name="column" min="1" max="15" value="1" required>

                <label for="row">Rada</label>
                <select list="rows" name="row" id="row">
                    <option value="A">A</option>
                    <option value="B">B</option>
                    <option value="C">C</option>
                    <option value="D">D</option>
                    <option value="E">E</option>
                    <option value="F">F</option>
                    <option value="G">G</option>
                </select>

                <label for="type">Typ platby</label>
                <select id="type" name="type">
                    <option value="na pokladně">Na pokladně</option>
                    <option value="předem">Předem</option>
                </select>

            </div>
            <div class="item">

            </div>
            <div class="item">
                <input type="submit" value="Potvrdit">
                <input type=button value="Zpet" onclick="window.location.href='search'">
            </div>
        </form>

    </div>
</div>
</body>
