<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="script" href="Views/JS/actions.js">
</head>
<body>

<div class="mx-auto">
    <h2 class="text-center mb-4">Vyhledávání kulturních událostí</h2>
    <form method="post" class="mx-auto" style="width: 600px">
        <div class="form-group row">
            <label for="date" class="col-3 col-form-label">Datum</label>
            <div class="col-9">
                <input type="date" name="date" id="date" class="form-control" value="<?= date('Y-m-d') ?>">
            </div>
        </div>
        <div class="form-group row">
            <label for="begin" class="col-3 col-form-label">Začátek</label>
            <div class="col-9">
                <input type="time" name="begin" id="begin" class="form-control">
            </div>
        </div>
        <div class="form-group row">
            <label for="type" class="col-3 col-form-label">Typ</label>
            <div class="col-9">
                    <select class="custom-select form-control" id="type" name="type">
                        <option></option>
                        <option value="Film">Film</option>
                        <option value="Prednaska">Přednáška</option>
                        <option value="Prezentace">Prezentace</option>
                        <option value="Divadelni predstaveni">Divadelní představení</option>
                        <option value="Stand-up">Stand-up</option>
                    </select>

            </div>
        </div>
        <div class="form-group row">
            <label for="name" class="col-3 col-form-label">Název</label>
            <div class="col-9">
                <input type="text" placeholder="Zadejte název události" name="name" id="name" class="form-control">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3"></div>
            <div class="col-9">
            <button type="submit" class="btn btn-primary">Hledat</i></button>
        </div>
    </form>
</div>

<table class="table mt-5 w-100">
    <div class="active">

    <!-- Zobrazeni nadpisu pouze pri zavolani getAllFutureEvents        -->
    <?php if(($_SERVER['REQUEST_METHOD'] === 'GET')) : ?>
        <h4>Nadcházející události</h4>
    <?php elseif (empty($_POST['date']) && empty($_POST['begin']) && empty($_POST['type']) && empty($_POST['name'])) : ?>
        <h4>Nadcházející události</h4>
    <?php endif ?>
        </div>
    <thead class="table-primary">
        <tr>
            <th></th>
            <th scope="col">Jméno</th>
            <th scope="col">Typ</th>
            <th scope="col">Žánr</th>
            <th scope="col">Datum</th>
            <th scope="col">Začátek</th>
            <th scope="col">Label</th>
            <th scope="col">Cena</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($events as $event) : ?>
        <tr>
            <td>
                <button class="btn btn-outline-secondary" onclick="location.href='search/event/<?php echo (str_replace(' ', '%20', $event['name'])) ?> ';">
                    <i class="fas fa-info"></i>
                </button>
            </td>
            <?php $id = $event['id'];
            unset($event['id'])?>
            <?php foreach ($event as $value) : ?>
            <td>
                <?php echo ($value); ?>
            </td>
            <?php endforeach ?>
            <td>
                <!-- Zasednuti tlacitka 'Rezervovat' pokud udalost jiz probehla/zacala -->
                <button class="btn btn-primary " onclick="location.href = 'reservation/create/<?= (str_replace(' ', '%20', $event['type']))
                ?>/<?=(str_replace(' ', '%20', $id)) ?>/<?=(str_replace(' ', '%20', $event['label']))?>/<?=
                (str_replace(' ' , '%20', $event['begin']))?>'"

                > Rezervovat
                </button>
            </td>

        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</body>