<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="script" href="Views/JS/actions.js">
</head>
<body>

<div id="ticketItem">
    <div class="mx-auto">
        <h1 class="text-center mb-4">Vyhledávání kulturních událostí</h1>
        <form method="post" class="mx-auto" style="width: 600px">
            <div class="form-group row">
                <label for="date" class="col-3 col-form-label">Datum</label>
                <div class="col-9">
                    <input type="date" name="date" id="date" class="form-control" value="<?= date('Y-m-d') ?>">
                </div>
            </div>
            <div class="form-group row">
                <label for="begin" class="col-3 col-form-label">Začátek</label>
                <div class="col-9">
                    <input type="time" name="begin" id="begin" class="form-control" value="<?= date('H:i') ?>">
                </div>
            </div>
            <div class="form-group row">
                <label for="type" class="col-3 col-form-label">Typ</label>
                <div class="col-9">
                    <select class="custom-select form-control" id="browsers">
                        <option value="Film">Film</option>
                        <option value="Prednaska">Přednáška</option>
                        <option value="Prezentace">Prezentace</option>
                        <option value="Divadelní představení">Divadelní představení</option>
                        <option value="Stand-up">Stand-up</option>
                    </select>   
                </div>
            </div>
            <div class="form-group row">
                <label for="name" class="col-3 col-form-label">Název</label>
                <div class="col-9">
                    <input type="text" placeholder="Zadejte nazev udalosti" name="name" id="name" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3"></div>
                <div class="col-9">
                <button type="submit" class="btn btn-primary">Hledat</i></button>
            </div>
        </form>
    </div>

    <table class="table mt-5 w-100">
        <thead class="table-primary">
            <tr>
                <th></th>
            <?php foreach ($events[0] as $item => $value) : ?>
                <th scope="col"> <?= $item ?> </th>
            <?php endforeach ?>
                <th></th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($events as $event) : ?>
            <tr>
                <td>
                    <button class="btn btn-outline-secondary" onclick="location.href= 'search/event/<?= str_replace(' ', '%20', $event['name']) ?> ';">
                        <i class="fas fa-info"></i>
                    </button>
                </td>
                <?php foreach ($event as $value) : ?>
                <td>
                    <?= $value ?>
                </td>                        
                <?php endforeach ?>
                <td>
                    <button class="btn btn-primary" onclick="location.href = 'reservation/create/
                        <?= str_replace(' ', '%20', $event['type']) ?>
                        /
                        <?= str_replace(' ', '%20', $event['name']) ?>
                        /
                        <?= $event['label'] ?>
                        /
                        <?= str_replace(' ', '%20', $event['begin']) ?>
                    ';">
                        Rezervovat
                    </button>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>

<script type="text/javascript" src="Views/JS/actions.js"></script>
</body>