<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>

<body>

<div class="mx-auto" style="width: 600px">
    <div class="container">
    <form method="post">
            <div class="row form-group">
                <div class="col-3">
                    <label for="old">Staré heslo</label>
                </div>
                <div class="col-9">
                    <input type="password" class="form-control" id="passowrd" name="password" placeholder="Staré heslo">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="newPassword">Nové heslo</label>
                </div>
                <div class="col-9">
                    <input type="password" class="form-control" id="newPassowrd" name="newPassword" placeholder="Nové heslo">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3">
                    <label for="newPasswordRetype">Potvrzení nového hesla</label>
                </div>
                <div class="col-9">
                    <input type="password" class="form-control" id="newPasswordRetype" name="newPasswordRetype" placeholder="Potvrzení nového hesla">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-3"></div>
                <div class="col-9">
                    <input type="submit" class="btn btn-primary" value="Uložit" onclick="window.location.href='settings'">
                    <input type="button" class="btn btn-secondary" value="Zpět" onclick="window.location.href='settings'">
            </div>
    </div>
</div>

</body>
