<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>

<body>
<form method="post">
    <div class="generalSettings">
        <div class="settings">
            <label for="old">Staré heslo:</label>
            <input type="password" id="password" name="password" placeholder="Staré heslo">
        </div>
        <div class="settings">
            <label for="newPassword">Nové heslo:</label>
            <input type="password" id="newPassword" name="newPassword" placeholder="Nové heslo">
        </div>
        <div class="settings">
            <label for="newPasswordRetype">Zopakujte nové heslo</label>
            <input type="password" id="newPasswordRetype" name="newPasswordRetype" placeholder="Zopakujte nové heslo">
        </div>
        <div>
            <input type=submit value="Uložit" onclick="window.location.href='settings'">
        </div>
        <div class="settings">
            <input type=button value="Zpět" onclick="window.location.href='settings'">
        </div>
    </div>
</form>
</body>
