<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>

<body>
<div class="generalSettings">
	<div class="settings">
		First Name: <?= $this->data['firstName'] ?>
	</div>
	<div class="settings">
		Last Name: <?= $this->data['lastName'] ?>
	</div>
	<div class="settings">
		Email: <?= $this->data['email'] ?>
	</div>
    <div class="settings">
        <input type="submit" value="Edit profile" onclick=window.location.href='settings/edit'>
        <input type="submit" value="Change password" onclick=window.location.href='settings/password'>
    </div>
</div>
</body>
