<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>

<body>
<form method="post">
    <div class="generalSettings">
        <div class="settings">
            <label for="old">Old password:</label>
            <input type="password" id="password" name="password" placeholder="type your old password">
        </div>
        <div class="settings">
            <label for="newPassword">New password:</label>
            <input type="password" id="newPassword" name="newPassword" placeholder="Type your new password">
        </div>
        <div class="settings">
            <label for="newPasswordRetype">Retype your password</label>
            <input type="password" id="newPasswordRetype" name="newPasswordRetype" placeholder="Retype your new
 password">
        </div>
        <div>
            <input type=submit value="Save" onclick="window.location.href='settings'">
        </div>
        <div class="settings">
            <input type=button value="Back" onclick="window.location.href='settings'">
        </div>
    </div>
</form>
</body>
