<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>

<body>

<div class="mx-auto" style="width: 600px">
    <div class="container">
        <div class="row form-group">
            <div class="col-3">
                <label for="name">Jméno</label>
            </div>
            <div class="col-9">
                <input type="text" class="form-control" disabled value="<?= $this->data['firstName'] ?>">
            </div>
        </div>
        <div class="row form-group">
            <div class="col-3">
                <label for="type">Příjmení</label>
            </div>
            <div class="col-9">
                <input type="text" class="form-control" disabled value="<?= $this->data['lastName'] ?>">
            </div>
        </div>
        <div class="row form-group">
            <div class="col-3">
                <label for="genre">E-mail</label>
            </div>
            <div class="col-9">
                <input type="text" class="form-control" disabled value="<?= $this->data['email'] ?>">
            </div>
        </div>
        <div class="row form-group">
            <div class="col-3"></div>
            <div class="col-9">
                <input type="submit" class="btn btn-primary" value="Upravit profil" onclick=window.location.href='settings/edit'>
                <input type="submit" class="btn btn-primary" value="Změnit heslo" onclick=window.location.href='settings/password'>
            </div>
    </div>
</div>

</div>
</body>
