<!DOCTYPE html>

<html lang="cs-cz">
<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>

<body>
<form method="post">
    <div class="generalSettings">
        <div class="settings">
            Jméno: <?= $this->data['firstName'] ?>
        </div>
        <div class="settings">
            Příjmení: <?= $this->data['lastName'] ?>
        </div>
        <div class="settings">
            <label for="email">Email:</label>
            <input type="text" id="email" name="email" value="<?= $this->data['email'] ?>">
        </div>
        <div class="settings">
            <label for="password">Heslo:</label>
            <input type="password" id="password" name="password" placeholder="heslo">
        </div>
        <div class="settings">
            <input type=submit value="Uložit" onclick="window.location.href='settings'">
        </div>
        <div class="settings">
            <input type=button value="Zpět" onclick="window.location.href='settings'">
        </div>
    </div>
</form>
</body>
