<!DOCTYPE html>

<html lang="cs-cz">

<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>

<body>

<div id="ticketItem" style="text-align: center">
        <h1>Seznam lístků</h1>


		<?php foreach ($ticket as $concrete) : ?>
            <div class="concreteItem">

                <?php if($concrete['is_paid'] === 'Ne' && $concrete['payment_type'] === 'předem'){ ?>
                <input type="button" onclick="location.href='ticket/confirm/<?php echo$concrete['id']?>'" value="Uhradit"/>
                <?php }?>

            <!-- Storno button se zobrazi pouze pokud udalost jeste neprobehla (nezacala)                -->
                <?php if($concrete['date'] > $todayDate){ ?>
                    <input type="button" onclick="location.href='ticket/storno/<?php echo$concrete['id']?>'" value="Stornovat"/>
                <?php }else if($concrete['begin'] >= $currentTime && $concrete['date'] >= $todayDate){ ?>
                    <input type="button" onclick="location.href='ticket/storno/<?php echo$concrete['id']?>'" value="Stornovat"/>
                <?php }?>
                <?php foreach ($concrete as $item => $value) : ?>
				<?= $this->langMapper($item) ?> : <?= $value ?> &nbsp;|
			<?php endforeach ?>
            </div>
		<?php endforeach ?>
    </div>
</body>