<!DOCTYPE html>

<html lang="cs-cz">

<head>
    <meta charset="UTF-8"/>
    <base href="/localhost"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
</head>

<body>

<div style="text-align: center">
    <div class="tickets">
        <h1>Seznam listku</h1>
		<?php foreach ($ticket as $concrete) : ?>
            ------------------------------------------------------------------------------------------------------------------------
            <br>
			<?php foreach ($concrete as $item => $value) : ?>
				<?= $item ?> : <?= $value ?> &nbsp;|
			<?php endforeach ?>
            <br>------------------------------------------------------------------------------------------------------------------------
            <br>
		<?php endforeach ?>
    </div>
</div>
</body>